fix(hyperlight-component-util): Fix emit_hl_unmarshal_value to return a tuple for boolean values
This updates the emit_hl_unmarshal_value function to return a tuple
containing the boolean value and a constant 1, which fixes the following
build error if a function that has a bool as its argument is called:

```
error[E0610]: `bool` is a primitive type and therefore doesn't have fields
```

Signed-off-by: Jiaxiao (mossaka) Zhou <duibao55328@gmail.com>